name: Action CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Run my own container action
        id: my-action
        uses: ./
        with:
          who-to-greet: '@ramchipy'
